{% set name = "kimpy" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 889906d60dd4a98dc0983ebf31294256d32966207da112e9a8d94f344ec9510e

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - kim-api >=2.3.0
  run:
    - python
    - pip
    - pybind11
    - pytest
    - numpy
    - kim-api >=2.3.0

test:
  imports:
    - kimpy
  commands:
    - pip check

about:
  home: https://github.com/openkim/kimpy
  license: CDDL-1.0
  license_family: OTHER
  license_file: LICENSE.CDDL
  summary: Python interface to the KIM API

  description: |
    kimpy is a Python interface to the KIM API.
  doc_url: https://github.com/openkim/kimpy
  dev_url: https://github.com/openkim/kimpy

extra:
  recipe-maintainers:
    - mjwen
    - ilia-nikiforov-umn
    - jan-janssen
