{% set name = "kimpy" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de24b22ef0c9e9333bfa123973fb69ec0d71f0342d205414152492c656d994b7

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - pybind11
    - kim-api =2.2.0
  run:
    - python
    - pip
    - pybind11
    - pytest
    - numpy
    - kim-api =2.2.0

test:
  imports:
    - kimpy
  commands:
    - pip check

about:
  home: https://github.com/openkim/kimpy
  license: CDDL-1.0
  license_family: OTHER
  license_file: LICENSE.CDDL
  summary: Python interface to the KIM API

  description: |
    kimpy is a Python interface to the KIM API.
  doc_url: https://github.com/openkim/kimpy
  dev_url: https://github.com/openkim/kimpy

extra:
  recipe-maintainers:
    - jan-janssen
